Repository microsoft/mu_plus, pull requests merged in 2022-11, with the labels that each got.

#82 Added a new SUIT progress bar UI element.
  MsGraphicsPkg/Include/UIToolKit/ProgressBar.h
  MsGraphicsPkg/Include/UIToolKit/SimpleUIToolKit.h
  MsGraphicsPkg/Library/SimpleUIToolKit/ProgressBar.c
  MsGraphicsPkg/Library/SimpleUIToolKit/SimpleUIToolKit.inf
Labels: enhancement, backport

#97 Fix MfciDxe Debug error print missing new line character
  MfciPkg/MfciDxe/MfciDxe.c
Labels: bug

#112 Enable Label Sync GitHub Action
  .github/workflows/label-sync.yml
Labels: type:enhancement

#80 Update reset notification list to be notified before NVMe
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.c
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.inf
Labels: type:bug
