Repository microsoft/mu_plus, pull requests merged in 2022-10, with the labels that each got.

#76 SUIT List Box element should support cell selection via keyboard even when cell type isn't checkbox.
  MsGraphicsPkg/Library/SimpleUIToolKit/ListBox.c
Labels: enhancement

#75 BugFix: SUIT bitmap draw was happening outside the SWM context.
  MsGraphicsPkg/Library/SimpleUIToolKit/Bitmap.c
Labels: bug

#79 Dropped preproduction section
  MfciPkg/Docs/Mfci_Integration_Guide.md
Labels: bug, documentation

#81 Added a new SUIT progress bar UI element.
  MsGraphicsPkg/Include/UIToolKit/ProgressBar.h
  MsGraphicsPkg/Include/UIToolKit/SimpleUIToolKit.h
  MsGraphicsPkg/Library/SimpleUIToolKit/ProgressBar.c
  MsGraphicsPkg/Library/SimpleUIToolKit/SimpleUIToolKit.inf
Labels: enhancement
