Repository microsoft/mu_plus, pull requests merged in 2022-12, with the labels that each got.

#116 Add PcdShellFvGuid to allow platforms to provide FV GUID to search shell image in
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.c
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.inf
  PcBdsPkg/PcBdsPkg.dec
Labels: type:enhancement

#118 Add logic for container build to Matrix-Build-Job.yml
  .azurepipelines/Matrix-Build-Job.yml
Labels: impact:non-functional

#96 Remove Page Audit Report Generator Print
  UefiTestingPkg/AuditTests/PagingAudit/Windows/PagingReportGenerator.py
Labels: type:bug, language:python

#123 Introducing MP management driver and unit test app
  UefiTestingPkg/FunctionalSystemTests/MpManagement/App/MpManagementTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/App/MpManagementTestApp.inf
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/AsmSupport.S
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/AsmSupport.masm
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/SuspendHandling.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/ApFunction.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.inf
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagementInternal.h
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Readme.md
  UefiTestingPkg/Include/Protocol/MpManagement.h
  UefiTestingPkg/UefiTestingPkg.ci.yaml
  UefiTestingPkg/UefiTestingPkg.dec
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: type:documentation, impact:testing

#94 Fix SUIT bitmap set bounds - shouldn't apply a second translation to the new bounds origin.
  MsGraphicsPkg/Library/SimpleUIToolKit/Bitmap.c
Labels: type:bug

#127 UefiTestingPkg: Add ARM and AARCH64 to Supported Archs
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:non-functional

#126 Fix SUIT bitmap set bounds - shouldn't apply a second translation to the new bounds origin.
  MsGraphicsPkg/Library/SimpleUIToolKit/Bitmap.c
Labels: type:bug
