Repository microsoft/mu_plus, pull requests merged in 2023-07, with the labels that each got.

#267 ci.yaml: add PrEval entry
  AdvLoggerPkg/AdvLoggerPkg.ci.yaml
  HidPkg/HidPkg.ci.yaml
  MfciPkg/MfciPkg.ci.yaml
  MsCorePkg/MsCorePkg.ci.yaml
  MsGraphicsPkg/MsGraphicsPkg.ci.yaml
  MsWheaPkg/MsWheaPkg.ci.yaml
  PcBdsPkg/PcBdsPkg.ci.yaml
  UefiTestingPkg/UefiTestingPkg.ci.yaml
  XmlSupportPkg/XmlSupportPkg.ci.yaml
Labels: impact:non-functional

#271 Added logic to delete the Memory Type Information variable on a capsule update.
  MsCorePkg/Library/PlatformBootManagerLib/BdsPlatform.c
  MsCorePkg/Library/PlatformBootManagerLib/BdsPlatform.h
Labels: impact:non-functional

#273 Fix CodeQL errors
  HidPkg/HidKeyboardDxe/HidKeyboard.c
  MsWheaPkg/MsWheaReport/MsWheaEarlyStorageMgr.c
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.c
Labels: impact:security, impact:non-functional

#274 [CHERRY-PICK] Fix CodeQL errors
  HidPkg/HidKeyboardDxe/HidKeyboard.c
  MsWheaPkg/MsWheaReport/MsWheaEarlyStorageMgr.c
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.c
Labels: impact:security, impact:non-functional

#275 Close ReadyToBoot and ExitBootServices events if a reset is notified.
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.c
Labels: type:design-change, impact:non-functional
