Repository microsoft/mu_plus, pull requests merged in 2023-03, with the labels that each got.

#189 Update the MemoryProtectionTestApp to use the MemoryAttributeProtocol for Architecture Agnosticism
  UefiTestingPkg/FunctionalSystemTests/MemoryProtectionTest/App/MemoryProtectionTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MemoryProtectionTest/App/MemoryProtectionTestApp.inf
Labels: impact:testing

#196 Update the Paging Audit Readme to Reflect Recent Changes
  UefiTestingPkg/AuditTests/PagingAudit/README.md
Labels: type:documentation, impact:non-functional

#190 Separate MemoryProtectionExceptionLib into AArch64 and X64 Implementations
  MsCorePkg/Library/MemoryProtectionExceptionHandlerLib/MemoryProtectionExceptionHandlerLib.inf
  MsCorePkg/Library/MemoryProtectionExceptionHandlerLib/MemoryProtectionExceptionHandlerLibAArch64.c
  MsCorePkg/Library/MemoryProtectionExceptionHandlerLib/MemoryProtectionExceptionHandlerLibCommon.c
  MsCorePkg/Library/MemoryProtectionExceptionHandlerLib/MemoryProtectionExceptionHandlerLibX64.c
  MsCorePkg/Library/MemoryProtectionExceptionHandlerLib/Readme.md
  MsCorePkg/MsCorePkg.dsc
Labels: type:documentation, impact:security

#199 Update DecodeUefiLog ReadMe.md - Simple Typo Fixes
  AdvLoggerPkg/Application/DecodeUefiLog/ReadMe.md
Labels: type:documentation, impact:non-functional

#192 Add MemoryAttributeProtocolFuncTestApp
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/AARCH64/PageSplitTest.c
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.h
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.inf
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/PageSplitTest.c
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/Readme.md
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/X64/PageSplitTest.c
  UefiTestingPkg/UefiTestingPkg.ci.yaml
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:testing, impact:non-functional

#201 Add AARCH64 RWX Test to DxePagingAuditApp
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/AArch64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.h
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/X64/DxePagingAuditTests.c
Labels: impact:testing, impact:non-functional

#202 MsGraphicsPkg: More CodeQL fixes
  MsGraphicsPkg/DisplayEngineDxe/FormDisplay.c
  MsGraphicsPkg/DisplayEngineDxe/InputHandler.c
  MsGraphicsPkg/Library/QrEncoderLib/QrEncoderLib.c
  MsGraphicsPkg/Library/SwmDialogsLib/MessageBox.c
  MsGraphicsPkg/SimpleWindowManagerDxe/WaitForEvent.c
Labels: impact:security

#204 HidPkg: More CodeQL fixes
  HidPkg/HidKeyboardDxe/HidKeyboard.c
  HidPkg/HidPkg.dsc
Labels: impact:security

#205 Update CodeQlFilters
  CodeQlFilters.yml
Labels: impact:security

#203 MsWheaPkg: More CodeQL fixes
  MsWheaPkg/MsWheaReport/MsWheaReportHER.c
Labels: impact:security
