Repository microsoft/mu_plus, pull requests merged in 2023-05, with the labels that each got.

#232 Bugfix: Change UT_LOG to DEBUG in MsWheaEarlyUnitTest Entry Point
  MsWheaPkg/Test/UnitTests/MsWheaEarlyStorageUnitTestApp/MsWheaEarlyUnitTestApp.c
Labels: type:bug

#241 MsCorePkg: Add LoadOptionVariablePolicyDxe
  MsCorePkg/LoadOptionVariablePolicyDxe/LoadOptionVariablePolicyDxe.c
  MsCorePkg/LoadOptionVariablePolicyDxe/LoadOptionVariablePolicyDxe.inf
  MsCorePkg/MsCorePkg.dsc
Labels: type:enhancement, impact:security

#244 [CHERRY-PICK] Continue power management on disabled APs
  UefiTestingPkg/FunctionalSystemTests/MpManagement/App/MpManagementTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.c
Labels: impact:testing, impact:non-functional
