Repository microsoft/mu_plus, pull requests merged in 2023-12, with the labels that each got.

#384 Adding policy check for advanced file logger
  AdvLoggerPkg/AdvLoggerPkg.ci.yaml
  AdvLoggerPkg/AdvLoggerPkg.dec
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.c
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.h
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.inf
  AdvLoggerPkg/AdvancedFileLogger/ReadMe.md
  AdvLoggerPkg/Include/Guid/AdvancedFileLoggerPolicy.h
Labels: type:documentation

#386 MsGraphicsPkg/SimpleUIToolKit: Move array bounds check before access
  MsGraphicsPkg/Library/SimpleUIToolKit/ListBox.c
Labels: type:bug, impact:non-functional

#374 Implement a new version of UefiHidDxeV2 with significant improvements to unit test capability and general architecture.
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
  Cargo.toml
  HidPkg/Crates/HidIo/src/lib.rs
  HidPkg/HidPkg.dsc
  HidPkg/UefiHidDxeV2/Cargo.toml
  HidPkg/UefiHidDxeV2/UefiHidDxeV2.inf
  HidPkg/UefiHidDxeV2/src/boot_services.rs
  HidPkg/UefiHidDxeV2/src/driver_binding.rs
  HidPkg/UefiHidDxeV2/src/hid.rs
  HidPkg/UefiHidDxeV2/src/hid_io.rs
  HidPkg/UefiHidDxeV2/src/keyboard/key_queue.rs
  HidPkg/UefiHidDxeV2/src/keyboard/mod.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
  HidPkg/UefiHidDxeV2/src/lib.rs
  HidPkg/UefiHidDxeV2/src/main.rs
  HidPkg/UefiHidDxeV2/src/pointer/absolute_pointer.rs
  HidPkg/UefiHidDxeV2/src/pointer/mod.rs
Labels: type:enhancement, type:documentation, impact:testing
