Repository microsoft/mu_plus, pull requests merged in 2023-01, with the labels that each got.

#135 Fix UnitTestingPkg misspells
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/SuspendHandling.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagementInternal.h
  UefiTestingPkg/UefiTestingPkg.ci.yaml
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:non-functional

#121 Add Arm64 Translation Table Data Collection via DxePagingAudit
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/AArch64/PagingAuditProcessor.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/AArch64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.h
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/X64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/Driver/DxePagingAuditDriver.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/DxePagingAuditDriver.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/DxePagingAuditTestApp.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/PagingAuditCommon.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/PagingAuditCommon.h
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Smm/Driver/SmmPagingAuditDriver.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Smm/SmmPagingAuditCommon.h
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/X64/PagingAuditProcessor.c
Labels: impact:testing

#128 Change GCD Type Print Formatting to Fix Paging Audit Parsing
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/PagingAuditCommon.c
Labels: impact:non-functional

#120 Add Arm64 Translation Table Parsing to Windows Paging Audit Scripts
  UefiTestingPkg/AuditTests/PagingAudit/Windows/BinaryParsing.py
  UefiTestingPkg/AuditTests/PagingAudit/Windows/DxePaging_template_AArch64.html
  UefiTestingPkg/AuditTests/PagingAudit/Windows/DxePaging_template_X64.html
  UefiTestingPkg/AuditTests/PagingAudit/Windows/MemoryRangeObjects.py
  UefiTestingPkg/AuditTests/PagingAudit/Windows/PagingReportGenerator.py
Labels: impact:non-functional, language:python

#140 Fix Spellcheck Error in X64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/AArch64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/X64/DxePagingAuditTests.c
Labels: impact:non-functional

#132 Add Stack and NULL Page Data Parsing to the DXE Paging Audit
  UefiTestingPkg/AuditTests/PagingAudit/Windows/MemoryRangeObjects.py
  UefiTestingPkg/AuditTests/PagingAudit/Windows/PagingReportGenerator.py
Labels: language:python

#134 Fix C3 resume error on certain platforms
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/AsmSupport.S
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/SuspendHandling.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.inf
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagementInternal.h
Labels: impact:testing

#148 Convert line endings from LF to CRLF
  MsCorePkg/MacAddressEmulationDxe/Test/MacAddressEmulationDxeHostTest.inf
  MsCorePkg/UnitTests/MsCorePkgHostTest.dsc
  MsGraphicsPkg/Library/SimpleUIToolKit/SimpleUIToolKit.inf
  Readme.rst
  UefiTestingPkg/FunctionalSystemTests/MpManagement/App/MpManagementTestApp.inf
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/AsmSupport.masm
Labels: impact:non-functional

#147 Updated readme to include changes for 202208
  Readme.rst
Labels: type:documentation, impact:non-functional

#145 Remove UpdateFacsHardwareSignatureLib from PcBdsPkg
  PcBdsPkg/Library/UpdateFacsHardwareSignatureLib/UpdateFacsHardwareSignatureLib.c
  PcBdsPkg/Library/UpdateFacsHardwareSignatureLib/UpdateFacsHardwareSignatureLib.inf
  PcBdsPkg/PcBdsPkg.dsc
Labels: impact:breaking-change, impact:non-functional

#143 Remove DfciPkg from MsBootPolicy
  PcBdsPkg/Include/Settings/BootMenuSettings.h
  PcBdsPkg/Library/BootManagerSettingsDxeLibNull/BootManagerSettingsDxeLibNull.c
  PcBdsPkg/Library/BootManagerSettingsDxeLibNull/BootManagerSettingsDxeLibNull.inf
  PcBdsPkg/MsBootPolicy/MsBootPolicy.h
  PcBdsPkg/MsBootPolicy/MsBootPolicy.inf
  PcBdsPkg/PcBdsPkg.dsc
Labels: impact:breaking-change, impact:non-functional

#144 Remove MsBootManagerSettingsDxeLib from PcBdsPkg
  PcBdsPkg/Library/MsBootManagerSettingsDxeLib/BootManagerSettings.c
  PcBdsPkg/Library/MsBootManagerSettingsDxeLib/MsBootManagerSettingsDxeLib.inf
  PcBdsPkg/PcBdsPkg.dsc
Labels: impact:breaking-change, impact:non-functional

#155 Remove DeviceBootManagerLib from PcBdsPkg
  PcBdsPkg/Library/DeviceBootManagerLib/DeviceBootManagerLib.c
  PcBdsPkg/Library/DeviceBootManagerLib/DeviceBootManagerLib.inf
  PcBdsPkg/PcBdsPkg.ci.yaml
  PcBdsPkg/PcBdsPkg.dsc
Labels: impact:non-functional
