Repository microsoft/mu_plus, pull requests merged in 2023-06, with the labels that each got.

#257 Reduce RWX Test UT_LOG Verbosity in DxePagingAuditTestApp
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/AArch64/DxePagingAuditTests.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/X64/DxePagingAuditTests.c
Labels: impact:testing

#256 Update BootAuditTestApp to Correctly Test Load Option Variables
  UefiTestingPkg/AuditTests/BootAuditTest/UEFI/BootAuditTestApp.c
  UefiTestingPkg/AuditTests/BootAuditTest/UEFI/BootAuditTestApp.inf
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:testing

#259 MsCorePkg/PlatformBootManagerLib: Remove boot mode condition for con var update [Rebase & FF]
  MsCorePkg/Library/PlatformBootManagerLib/BdsPlatform.c
Labels: type:design-change

#260 [CHERRY-PICK] Remove bootmode from con var update 202302 [Rebase & FF]
  MsCorePkg/Library/PlatformBootManagerLib/BdsPlatform.c
Labels: type:design-change

#268 AdvLoggerPkg: fix AdvLoggerSerialPortLib class
  AdvLoggerPkg/Library/AdvLoggerSerialPortLib/AdvLoggerSerialPortLib.c
  AdvLoggerPkg/Library/AdvLoggerSerialPortLib/AdvLoggerSerialPortLib.inf
Labels: impact:breaking-change, impact:non-functional

#269 .github/label-issues.yml: Use Mu DevOps 4.0.5
  .github/workflows/label-issues.yml
Labels: type:dependencies, impact:non-functional
