Repository microsoft/mu_plus, pull requests merged in 2023-10, with the labels that each got.

#323 Feature/MsApplicationPkg/SecureBootRecovery
  .pytool/CISettings.py
  MsApplicationPkg/Docs/Readme.md
  MsApplicationPkg/MsApplicationPkg.ci.yaml
  MsApplicationPkg/MsApplicationPkg.dec
  MsApplicationPkg/MsApplicationPkg.dsc
  MsApplicationPkg/MsApplicationPkg.uni
  MsApplicationPkg/MsApplicationPkgExtra.uni
  MsApplicationPkg/ReadMe.rst
  MsApplicationPkg/SecureBootRecovery/Payload/DBUpdate.bin
  MsApplicationPkg/SecureBootRecovery/Readme.md
  MsApplicationPkg/SecureBootRecovery/RecoveryPayload.h
  MsApplicationPkg/SecureBootRecovery/SecureBootRecovery.c
  MsApplicationPkg/SecureBootRecovery/SecureBootRecovery.inf
  MsApplicationPkg/SecureBootRecovery/helper.py
Labels: language:python

#331 AdvLoggerPkg: BaseAdvancedLoggerLib: Fixing a missed PCD for AARCH64 usage
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.inf
Labels: type:bug, impact:non-functional

#332 Document current data flow of debug logging filtering
  AdvLoggerPkg/Docs/ReadMe.md
  AdvLoggerPkg/Docs/debug_log_level.png
Labels: type:documentation, impact:non-functional

#334 HidPkg/UsbHidDxe: Continue on failure to get descriptor
  HidPkg/UsbHidDxe/UsbHidDxe.c
Labels: impact:non-functional, semver:patch

#336 Use Absolute Pointer Protocol from r-efi 4.3.0
  Cargo.toml
  HidPkg/Crates/AbsolutePointer/Cargo.toml
  HidPkg/Crates/AbsolutePointer/src/lib.rs
  HidPkg/UefiHidDxe/Cargo.toml
  HidPkg/UefiHidDxe/src/pointer.rs
Labels: impact:non-functional

#339 UefiHidDxe: Change HID descriptor read algorithm
  HidPkg/UsbHidDxe/UsbHidDxe.c
Labels: type:enhancement

#341 Update HelloWorldRustDxe to permit compiling for unit tests
  MsCorePkg/HelloWorldRustDxe/Cargo.toml
  MsCorePkg/HelloWorldRustDxe/src/main.rs
Labels: impact:testing, impact:non-functional

#340 Add PCD to allow device exclusions for UsbHidDxe
  HidPkg/HidPkg.dec
  HidPkg/UsbHidDxe/UsbHidDxe.c
  HidPkg/UsbHidDxe/UsbHidDxe.inf
Labels: impact:breaking-change

#342 Add HiiKeyboardLayout crate to support UEFI HII Keyboard Layouts
  Cargo.toml
  HidPkg/Crates/HiiKeyboardLayout/Cargo.toml
  HidPkg/Crates/HiiKeyboardLayout/resources/test/KeyboardLayout.bin
  HidPkg/Crates/HiiKeyboardLayout/resources/test/KeyboardLayout.txt
  HidPkg/Crates/HiiKeyboardLayout/resources/test/KeyboardLayoutNs.bin
  HidPkg/Crates/HiiKeyboardLayout/resources/test/KeyboardLayoutNs.txt
  HidPkg/Crates/HiiKeyboardLayout/src/lib.rs
Labels: type:documentation, impact:testing
