Repository microsoft/mu_plus, pull requests merged in 2023-11, with the labels that each got.

#348 AdvLoggerPkg: Add PanicLib instance
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/Docs/ReadMe.md
  AdvLoggerPkg/Library/BasePanicLibAdvancedLogger/BasePanicLibAdvancedLogger.c
  AdvLoggerPkg/Library/BasePanicLibAdvancedLogger/BasePanicLibAdvancedLogger.inf
Labels: type:documentation, type:feature-request

#347 Add HID Keyboard support to UefiHidDxe
  Cargo.toml
  HidPkg/Crates/HiiKeyboardLayout/src/lib.rs
  HidPkg/UefiHidDxe/Cargo.toml
  HidPkg/UefiHidDxe/src/driver_binding.rs
  HidPkg/UefiHidDxe/src/hid.rs
  HidPkg/UefiHidDxe/src/key_queue.rs
  HidPkg/UefiHidDxe/src/keyboard.rs
  HidPkg/UefiHidDxe/src/main.rs
Labels: type:documentation

#355 Add log retrieval info to main readme
  AdvLoggerPkg/Docs/ReadMe.md
Labels: type:documentation, impact:non-functional

#359 Fixed logic related to DxeCore only advanced logger
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
Labels: type:bug

#358 Resolve deadlock in RustBootServicesAllocatorDxe
  MsCorePkg/Crates/RustBootServicesAllocatorDxe/Cargo.toml
  MsCorePkg/Crates/RustBootServicesAllocatorDxe/src/lib.rs
Labels: impact:testing, impact:non-functional

#356 Fix rust advlogger deadlock
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
Labels: type:bug, type:design-change, impact:non-functional

#361 Add SetProtocol command to force devices to Report Mode
  HidPkg/UsbHidDxe/UsbHidDxe.c
Labels: type:enhancement, impact:non-functional

#367 Use New Stack Cookie Library
  AdvLoggerPkg/AdvLoggerPkg.dsc
  HidPkg/HidPkg.dsc
  MfciPkg/MfciPkg.dsc
  MfciPkg/UnitTests/MfciPkgHostTest.dsc
  MsApplicationPkg/MsApplicationPkg.dsc
  MsCorePkg/MsCorePkg.dsc
  MsCorePkg/UnitTests/MsCorePkgHostTest.dsc
  MsGraphicsPkg/MsGraphicsPkg.dsc
  MsWheaPkg/MsWheaPkg.dsc
  PcBdsPkg/PcBdsPkg.dsc
  TpmTestingPkg/TpmTestingPkg.dsc
  UefiTestingPkg/UefiTestingPkg.dsc
  XmlSupportPkg/XmlSupportPkg.dsc
Labels: impact:security

#371 Add Unaccepted Memory Type to Memory Protection Test App
  UefiTestingPkg/FunctionalSystemTests/MemoryProtectionTest/App/MemoryProtectionTestApp.c
  UefiTestingPkg/FunctionalSystemTests/MemoryProtectionTest/MemoryProtectionTestCommon.h
Labels: type:bug

#363 RustAdvancedLoggerDxe: Remove spinlocks, add `function!()`, add `std` feature.
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/Cargo.toml
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
Labels: type:documentation, impact:testing

#373 Create separate FrameBufferMemDrawLib inf for PEI and DXE
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLib.c
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibDxe.c
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibDxe.inf
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibPei.inf
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibPeim.c
  MsGraphicsPkg/MsGraphicsPkg.dsc
Labels: impact:breaking-change, impact:non-functional
