Repository microsoft/mu_plus, pull requests merged in 2023-02, with the labels that each got.

#165 .azurepipelines: Add support for new artifacts_identifier param
  .azurepipelines/Matrix-Build-Job.yml
Labels: type:enhancement, impact:breaking-change, impact:non-functional

#171 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: type:enhancement

#173 [CodeQL] XmlSupportPkg: Fixing CodeQL failures in this package
  XmlSupportPkg/Library/XmlTreeLib/XmlTreeLib.c
  XmlSupportPkg/Library/XmlTreeLib/fasterxml/xml_fasterxml.c
  XmlSupportPkg/Library/XmlTreeLib/fasterxml/xml_xmlstructure.c
Labels: impact:security

#175 [CodeQL] MsWheaPkg: Fixing CodeQL failures in this package
  MsWheaPkg/HwhMenu/HwhMenu.c
  MsWheaPkg/Library/ParserRegistryLib/ParserRegistryLib.c
  MsWheaPkg/MsWheaReport/MsWheaEarlyStorageMgr.c
  MsWheaPkg/MsWheaReport/MsWheaReportHER.c
  MsWheaPkg/Test/UnitTests/MsWheaEarlyStorageUnitTestApp/MsWheaEarlyUnitTestApp.c
  MsWheaPkg/Test/UnitTests/MsWheaReportUnitTestApp/MsWheaReportUnitTestApp.c
Labels: impact:security

#176 [CodeQL] MsCorePkg: Fixing CodeQL failures in this package
  MsCorePkg/Core/GuidedSectionExtractPeim/GuidedSectionExtract.c
  MsCorePkg/MacAddressEmulationDxe/MacAddressEmulationDxe.c
Labels: impact:security

#177 [CodeQL] PcBdsPkg: Fixing CodeQL failures in this package
  PcBdsPkg/MsBootPolicy/MsBootPolicy.c
Labels: impact:security

#178 [CodeQL] CodeQL Fixes in HidPkg
  .pytool/CISettings.py
  CodeQlFilters.yml
  HidPkg/HidKeyboardDxe/HidKeyboard.c
Labels: impact:security

#179 [CodeQL] MsGraphicsPkg CodeQL Fixes
  MsGraphicsPkg/DisplayEngineDxe/FormDisplay.c
  MsGraphicsPkg/Library/BaseUiRectangleLib/UiRectangle.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Utilities.c
  MsGraphicsPkg/MsEarlyGraphics/MsEarlyGraphicsCommon.c
Labels: impact:security

#180 AdvLoggerPkg: Additional CodeQL fixes
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
Labels: impact:security

#174 UefiTestingPkg: Additional CodeQL fixes
  UefiTestingPkg/AuditTests/DMAProtectionAudit/UEFI/IVRS/DMAProtectionTestArch.c
  UefiTestingPkg/AuditTests/DMAProtectionAudit/UEFI/IVRS/IVRSAcpiTable.c
  UefiTestingPkg/AuditTests/DMAProtectionAudit/UEFI/VTd/DMAProtectionTestArch.c
  UefiTestingPkg/AuditTests/DMAProtectionAudit/UEFI/VTd/DmarAcpiTable.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/PagingAuditCommon.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Smm/Driver/SmmPagingAuditDriver.c
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/X64/PagingAuditProcessor.c
  UefiTestingPkg/FunctionalSystemTests/MemoryProtectionTest/App/MemoryProtectionTestApp.c
Labels: impact:security

#187 .pytool/CISettings.py: Use all CodeQL filter files
  .pytool/CISettings.py
Labels: impact:non-functional
