Repository microsoft/mu_plus, pull requests merged in 2023-08, with the labels that each got.

#277 Add a check on the `PcdAdvancedFileLoggerFlush` for exit boot services
  AdvLoggerPkg/AdvLoggerPkg.dec
  AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.c
Labels: type:bug

#280 PcBdsPkg: Fix previous CodeQL change (51c7dc2)
  PcBdsPkg/Include/Library/MsBootPolicyLib.h
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.c
Labels: type:bug

#281 [Cherry-pick] PcBdsPkg: Fix previous CodeQL change (b6b6c9c)
  PcBdsPkg/Include/Library/MsBootPolicyLib.h
  PcBdsPkg/Library/MsBootOptionsLib/MsBootOptionsLib.c
Labels: type:bug

#282 MsGraphicsPkg/FrameBufferMemDrawLib: Fix function declaration mismatch
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLib.h
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibDxe.c
  MsGraphicsPkg/Library/FrameBufferMemDrawLib/FrameBufferMemDrawLibPeim.c
Labels: impact:non-functional

#290 Update UXN/PXN Parsing and Fix Filters in Paging Audit
  UefiTestingPkg/AuditTests/PagingAudit/Windows/DxePaging_template_AArch64.html
  UefiTestingPkg/AuditTests/PagingAudit/Windows/DxePaging_template_X64.html
  UefiTestingPkg/AuditTests/PagingAudit/Windows/MemoryRangeObjects.py
Labels: impact:testing, language:python

#293 AdvLoggerPkg: Switch to using AsciiStrnLenS
  AdvLoggerPkg/Library/AssertLib/AssertLib.c
  AdvLoggerPkg/Library/AssertTelemetryLib/AssertLib.c
  AdvLoggerPkg/Library/BaseDebugLibAdvancedLogger/DebugLib.c
Labels: complexity:easy

#295 TpmTestingPkg/TpmReplay: Add schema documentation
  TpmTestingPkg/TpmReplayPei/Tool/TpmReplaySchema.md
  TpmTestingPkg/TpmTestingPkg.ci.yaml
Labels: type:documentation, impact:non-functional

#302 MsCorePkg: Remove invalid library instance in DSC
  MsCorePkg/MsCorePkg.dsc
Labels: type:bug, impact:non-functional

#304 Integrate UefiCpuLib breaking change
  MsCorePkg/MsCorePkg.dsc
  TpmTestingPkg/TpmTestingPkg.dsc
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/DxePagingAuditDriver.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/DxePagingAuditTestApp.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/SmmPagingAuditDriver.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/SmmPagingAuditTestApp.inf
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/X64/PagingAuditProcessor.c
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:non-functional, semver:patch
