Repository microsoft/mu_plus, pull requests merged in 2024-09, with the labels that each got.

#572 Add MockDeviceBootManagerLib
  MsCorePkg/MsCorePkg.dec
  MsCorePkg/UnitTests/Mock/Include/GoogleTest/Library/MockDeviceBootManagerLib.h
  MsCorePkg/UnitTests/Mock/Library/MockDeviceBootManagerLib/MockDeviceBootManagerLib.cpp
  MsCorePkg/UnitTests/Mock/Library/MockDeviceBootManagerLib/MockDeviceBootManagerLib.inf
  MsCorePkg/UnitTests/MsCorePkgHostTest.dsc
Labels: impact:non-functional

#555 AdvLoggerPkg: Add GoogleTest for AdvancedLoggerPeiLib
  AdvLoggerPkg/AdvLoggerPkg.ci.yaml
  AdvLoggerPkg/Library/AdvancedLoggerLib/Pei/GoogleTest/AdvancedLoggerPeiLibGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/Pei/GoogleTest/AdvancedLoggerPeiLibGoogleTest.inf
  AdvLoggerPkg/Test/AdvLoggerHostTest.dsc
  AdvLoggerPkg/Test/Mock/Include/GoogleTest/Ppi/MockAdvancedLogger.h
Labels: impact:testing, impact:non-functional

#569 Add DxeCore AdvancedLogger GoogleTest
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/GoogleTest/AdvancedLoggerDxeCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/GoogleTest/AdvancedLoggerDxeCoreGoogleTest.inf
  AdvLoggerPkg/Test/AdvLoggerHostTest.dsc
  AdvLoggerPkg/Test/Mock/Include/GoogleTest/Library/MockAdvancedLoggerHdwPortLib.h
  AdvLoggerPkg/Test/Mock/Library/GoogleTest/MockAdvancedLoggerHdwPortLib/MockAdvancedLoggerHdwPortLib.cpp
  AdvLoggerPkg/Test/Mock/Library/GoogleTest/MockAdvancedLoggerHdwPortLib/MockAdvancedLoggerHdwPortLib.inf
Labels: impact:testing, impact:non-functional

#576 AdvLoggerPkg: Add GoogleTest for AdvancedLoggerPeiCoreLib
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/GoogleTest/AdvancedLoggerPeiCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/GoogleTest/AdvancedLoggerPeiCoreGoogleTest.inf
  AdvLoggerPkg/Test/AdvLoggerHostTest.dsc
Labels: impact:testing, impact:non-functional

#577 AdvLoggerPkg: Add AdvancedLoggerMmCoreGoogleTest
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/GoogleTest/AdvancedLoggerMmCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/GoogleTest/AdvancedLoggerMmCoreGoogleTest.inf
  AdvLoggerPkg/Test/AdvLoggerHostTest.dsc
Labels: impact:testing, impact:non-functional

#583 RustAdvancedLoggerDxe: Update to use mu_rust_helpers
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/Cargo.toml
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
  Cargo.toml
Labels: impact:testing, impact:non-functional

#585 AdvLoggerPkg: Run AARCH64 CI
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/GoogleTest/AdvancedLoggerDxeCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/GoogleTest/AdvancedLoggerMmCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Runtime/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/SmmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/DebugAgent/Sec/AdvancedLoggerSecDebugAgent.c
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: type:bug, impact:testing, impact:non-functional

#589 [CHERRY-PICK] AARCH64 AdvLoggerPkg CI
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/GoogleTest/AdvancedLoggerDxeCoreGoogleTest.cpp
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Runtime/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/SmmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/DebugAgent/Sec/AdvancedLoggerSecDebugAgent.c
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: impact:non-functional

#590 AdvLoggerPkg: Run CI for AARCH64
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Runtime/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/SmmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/DebugAgent/Sec/AdvancedLoggerSecDebugAgent.c
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: impact:non-functional

#591 AdvLoggerPkg: Clarify BaseArm instance of AdvLoggerLib
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.inf
Labels: impact:non-functional
