Repository microsoft/mu_plus, pull requests merged in 2024-04, with the labels that each got.

#457 When recovering Pei buffer from hob list, need to fix internal pointe…
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
Labels: impact:non-functional

#453 Advanced Logger Binary Dump Windows Executable
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin.sln
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/AdvLoggerDumpWin.vcxproj
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/PropertySheet.props
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/ReadMe.md
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/main.cpp
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/main.h
  AdvLoggerPkg/Application/Windows/AdvLoggerDumpWin/packages.config
Labels: type:documentation, impact:non-functional

#460 Update the Mem Map and MAT Shell Test to Support RUNTIME_PAGE_ALLOCATION_GRANULARITY Alignment
  UefiTestingPkg/FunctionalSystemTests/MemmapAndMatTestApp/MemmapAndMatTestApp.c
Labels: impact:testing, impact:non-functional

#473 Moving the global variable from header file into library instances
  MfciPkg/Include/Library/MfciDeviceIdSupportLib.h
  MfciPkg/Library/MfciDeviceIdSupportLibNull/MfciDeviceIdSupportLibNull.c
  MfciPkg/Library/MfciDeviceIdSupportLibSmbios/MfciDeviceIdSupportLibSmbios.c
  MfciPkg/MfciDxe/MfciTargeting.c
  MfciPkg/MfciDxe/Test/MfciMultipleCertsHostTest.c
  MfciPkg/Private/MfciPolicyFields.h
  MfciPkg/UnitTests/MfciPkgHostTest.dsc
  MfciPkg/UnitTests/MfciPolicyParsingUnitTest/MfciPolicyParsingUnitTestApp.inf
Labels: type:documentation, impact:non-functional
