Repository microsoft/mu_plus, pull requests merged in 2024-10, with the labels that each got.

#568 [CHERRY-PICK] DxePagingAuditTestApp: Remove MemoryOutsideEfiMemoryMapIsInaccessibleTest
  UefiTestingPkg/AuditTests/PagingAudit/README.md
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
Labels: impact:testing, impact:non-functional

#594 [CHERRY-PICK] Remove MemoryOutsideEfiMemoryMapIsInaccessible Test
  UefiTestingPkg/AuditTests/PagingAudit/README.md
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
Labels: impact:testing, impact:non-functional

#584 Move MockDeviceBootManagerLib Path
  MsCorePkg/MsCorePkg.dec
  MsCorePkg/Test/Mock/Include/GoogleTest/Library/MockDeviceBootManagerLib.h
  MsCorePkg/Test/Mock/Library/GoogleTest/MockDeviceBootManagerLib/MockDeviceBootManagerLib.cpp
  MsCorePkg/Test/Mock/Library/GoogleTest/MockDeviceBootManagerLib/MockDeviceBootManagerLib.inf
  MsCorePkg/UnitTests/MsCorePkgHostTest.dsc
Labels: impact:non-functional

#598 MfciPkg: Correct Mfci script for switchover to using edk2toollib Variable service
  MfciPkg/Application/MfciPolicy/MfciPolicy.py
Labels: impact:non-functional, language:python

#602 TpmTestingPkg: Enhance decode of PCR7 vars
  TpmTestingPkg/TpmReplayPei/Tool/TpmReplay.py
Labels: language:python

#601 [Cherry-Pick] MfciPkg: Correct Mfci script for switchover to using edk2toollib Variable Services
  MfciPkg/Application/MfciPolicy/MfciPolicy.py
Labels: impact:non-functional, language:python

#606 Fix MfciPolicy.py syntax error
  MfciPkg/Application/MfciPolicy/MfciPolicy.py
Labels: impact:non-functional, language:python
