Repository microsoft/mu_plus, pull requests merged in 2024-12, with the labels that each got.

#611 MsWheaPkg: Add Rust Telemetry helper library
  Cargo.toml
  MsWheaPkg/Crates/MuTelemetryHelperLib/Cargo.toml
  MsWheaPkg/Crates/MuTelemetryHelperLib/src/lib.rs
  MsWheaPkg/Crates/MuTelemetryHelperLib/src/status_code_runtime.rs
Labels: type:documentation, impact:testing, impact:non-functional

#610 Add MsBootHttp4 MsBootHttp6 boot sequence
  PcBdsPkg/Include/Library/MsBootPolicyLib.h
Labels: impact:non-functional, type:backport

#593 UefiHidDxeV2: Remove mutable static shared reference
  HidPkg/UefiHidDxeV2/src/keyboard.rs
Labels: impact:non-functional, semver:patch

#615 AdvancedLogDumper: Fixed application logic to not bail all the time
  AdvLoggerPkg/Application/AdvancedLogDumper/LogDumper.c
Labels: type:bug, type:backport
