Repository microsoft/mu_plus, pull requests merged in 2024-05, with the labels that each got.

#480 AdvLoggerPkg: Fixed Document for SMM_CORE library instance
  AdvLoggerPkg/Docs/ReadMe.md
Labels: type:documentation, impact:non-functional

#479 Sample MfciPolicy script for interacting with Mfci from windows
  MfciPkg/Application/MfciPolicy/MfciPolicy.py
  MfciPkg/Application/MfciPolicy/Readme.md
  MfciPkg/Application/MfciPolicy/UefiVariableSupport/UefiVariablesSupportLib.py
Labels: type:documentation, impact:non-functional, language:python

#484 [REBASE ON MERGE] Fix Incorrect mHighAddress Calculation
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
Labels: type:bug

#488 Update MorLockTestApp to fix errors with new standard return values
  UefiTestingPkg/FunctionalSystemTests/MorLockTestApp/MorLockTestApp.c
Labels: impact:testing, impact:non-functional
