Repository microsoft/mu_plus, pull requests merged in 2024-07, with the labels that each got.

#522 MfciPkg: Removed TargetVerifyPhaseSuite Tests suite since it did not contain any tests.
  MfciPkg/MfciDxe/Test/MfciVerifyPolicyAndChangeHostTest.c
  MfciPkg/MfciDxe/Test/MfciVerifyPolicyAndChangeRoTHostTest.c
  MsWheaPkg/MsWheaReport/Test/MsWheaReportCommonHostTest.c
  pip-requirements.txt
Labels: impact:testing, impact:non-functional

#523 Add debug level prefix for advanced logger memory message entries
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
Labels: impact:non-functional, language:python

#512 MsGraphicsPkg: Fix issues in coordinate calculation
  MsGraphicsPkg/DisplayEngineDxe/FormDisplay.c
  MsGraphicsPkg/Include/Protocol/SimpleWindowManager.h
  MsGraphicsPkg/Library/SimpleUIToolKit/Bitmap.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Button.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Canvas.c
  MsGraphicsPkg/Library/SimpleUIToolKit/EditBox.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Grid.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Label.c
  MsGraphicsPkg/Library/SimpleUIToolKit/ListBox.c
  MsGraphicsPkg/Library/SimpleUIToolKit/ProgressBar.c
  MsGraphicsPkg/Library/SimpleUIToolKit/ToggleSwitch.c
  MsGraphicsPkg/Library/SimpleUIToolKit/Utilities.c
  MsGraphicsPkg/Library/SwmDialogsLib/MessageBox.c
  MsGraphicsPkg/Library/SwmDialogsLib/PasswordDialog.c
  MsGraphicsPkg/Library/SwmDialogsLib/SemmUserAuthDialog.c
  MsGraphicsPkg/Library/SwmDialogsLib/SingleSelectDialog.c
  MsGraphicsPkg/OnScreenKeyboardDxe/OnScreenKeyboardDriver.c
  MsGraphicsPkg/RenderingEngineDxe/RenderingEngine.c
Labels: impact:non-functional

#524 MsCorePkg: Update telemetry logging with PI Spec EFI Status Code
  MsCorePkg/Library/MemoryTypeInformationChangeLib/MemoryTypeInformationChangeLib.c
Labels: impact:breaking-change, impact:non-functional

#528 UefiTestingPkg: DxePagingAuditTestApp Fix Inaccessible Memory Test
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
Labels: type:bug, impact:testing, impact:non-functional

#530 AdvLoggerPkg: AssertLib update PI Status Code to match PI spec
  AdvLoggerPkg/Library/AssertTelemetryLib/AssertLib.c
Labels: impact:non-functional

#504 UEFI HID DXE V2 to improve Idiomatic Rust patterns
  HidPkg/UefiHidDxeV2/src/boot_services.rs
  HidPkg/UefiHidDxeV2/src/hid.rs
  HidPkg/UefiHidDxeV2/src/hid_io.rs
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/key_queue.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
  HidPkg/UefiHidDxeV2/src/lib.rs
  HidPkg/UefiHidDxeV2/src/main.rs
  HidPkg/UefiHidDxeV2/src/pointer.rs
  HidPkg/UefiHidDxeV2/src/pointer/absolute_pointer.rs
Labels: impact:non-functional

#533 [CHERRY-PICK] UEFI HID DXE V2 to improve Idiomatic Rust patterns
  HidPkg/UefiHidDxeV2/src/boot_services.rs
  HidPkg/UefiHidDxeV2/src/hid.rs
  HidPkg/UefiHidDxeV2/src/hid_io.rs
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/key_queue.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
  HidPkg/UefiHidDxeV2/src/lib.rs
  HidPkg/UefiHidDxeV2/src/main.rs
  HidPkg/UefiHidDxeV2/src/pointer.rs
  HidPkg/UefiHidDxeV2/src/pointer/absolute_pointer.rs
Labels: impact:non-functional
