Repository microsoft/mu_plus, pull requests merged in 2024-08, with the labels that each got.

#525 Add debug level prefix for advanced logger memory message entries - Driver implementation
  AdvLoggerPkg/AdvLoggerPkg.ci.yaml
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
Labels: language:python

#544 Fix a debug string format specifier.
  MfciPkg/Library/MfciDeviceIdSupportLibSmbios/MfciDeviceIdSupportLibSmbios.c
Labels: type:bug, impact:non-functional

#500 Switch to use edk2-pytool-library UefiVariableSupportLib
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Application/DecodeUefiLog/UefiVariablesSupportLib.py
  MfciPkg/Application/MfciPolicy/MfciPolicy.py
  MfciPkg/Application/MfciPolicy/UefiVariableSupport/UefiVariablesSupportLib.py
  UefiTestingPkg/AuditTests/UefiVarLockAudit/Windows/UefiVarAudit.py
  UefiTestingPkg/AuditTests/UefiVarLockAudit/Windows/UefiVariablesSupportLib.py
Labels: language:python

#545 [Cherry-Pick] Fix a debug string format specifier.
  MfciPkg/Library/MfciDeviceIdSupportLibSmbios/MfciDeviceIdSupportLibSmbios.c
Labels: impact:non-functional

#548 Adding MuArmGicExLib and update the usage accordingly
  MsCorePkg/Include/Library/MuArmGicExLib.h
  MsCorePkg/Library/MuArmGicExLib/AArch64/MuArmGicEx.S
  MsCorePkg/Library/MuArmGicExLib/AArch64/MuArmGicEx.masm
  MsCorePkg/Library/MuArmGicExLib/MuArmGicExLib.c
  MsCorePkg/Library/MuArmGicExLib/MuArmGicExLib.inf
  MsCorePkg/MsCorePkg.ci.yaml
  MsCorePkg/MsCorePkg.dec
  MsCorePkg/MsCorePkg.dsc
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/AARCH64/SuspendHandling.c
  UefiTestingPkg/FunctionalSystemTests/MpManagement/Driver/MpManagement.inf
  UefiTestingPkg/UefiTestingPkg.ci.yaml
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:breaking-change

#547 Updated logic to allocate more data once it needs to query memory map
  UefiTestingPkg/FunctionalSystemTests/MemmapAndMatTestApp/MemmapAndMatTestApp.c
Labels: type:bug, impact:testing

#549 AdvLoggerPkg: Modify AdvancedLib Dxe initialization.
  AdvLoggerPkg/Library/AdvancedLoggerLib/Dxe/AdvancedLoggerLib.c
Labels: impact:non-functional

#552 MsGraphicsPkg: Correct positioning of trash can icon in Load Option's list box
  MsGraphicsPkg/Library/SimpleUIToolKit/ListBox.c
Labels: type:bug

#551 Updated Release Notes.
  Readme.rst
Labels: impact:non-functional

#562 pip: Update all pip-requirements to latest.
  pip-requirements.txt
Labels: impact:non-functional

#541 Removed reference to PcdAdvancedHdwLoggerDisable in the README
  AdvLoggerPkg/Docs/ReadMe.md
Labels: type:documentation, impact:non-functional

#540 Removed All References to PcdAdvancedLoggerPeiInRam
  AdvLoggerPkg/AdvLoggerPkg.dec
  AdvLoggerPkg/Docs/ReadMe.md
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.inf
Labels: type:documentation, impact:breaking-change, impact:non-functional

#532 DxePagingAuditTestApp: Remove MemoryOutsideEfiMemoryMapIsInaccessible Test
  UefiTestingPkg/AuditTests/PagingAudit/README.md
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
Labels: type:bug, type:documentation, impact:testing, impact:non-functional

#565 AdvLoggerPkg: Exit from write call if signature mismatch
  AdvLoggerPkg/Library/AdvancedLoggerLib/Pei/AdvancedLoggerLib.c
Labels: type:bug
