Repository microsoft/mu_plus, pull requests merged in 2024-06, with the labels that each got.

#492 Fixing bsr64 for MathLib
  MsCorePkg/Library/MathLib/MathLib.c
  MsCorePkg/MsCorePkg.ci.yaml
Labels: type:bug

#494 Fix GCC Build of AdvLoggerOsConnectorPRM
  AdvLoggerPkg/AdvLoggerOsConnectorPrm/AdvLoggerOsConnectorPrm.inf
Labels: impact:non-functional

#497 Fixing precedence of "not" and bitwise operators
  UefiTestingPkg/FunctionalSystemTests/MemoryAttributeProtocolFuncTestApp/X64/PageSplitTest.c
Labels: impact:testing

#505 MfciPkg & MsCorePkg: Fix unit test compilation errors.
  MfciPkg/MfciDxe/Test/MfciVerifyPolicyAndChangeHostTest.c
  MfciPkg/MfciDxe/Test/MfciVerifyPolicyAndChangeRoTHostTest.c
  MsCorePkg/MacAddressEmulationDxe/Test/MacAddressEmulationDxeHostTest.inf
Labels: impact:non-functional

#498 Apply more idiomatic Rust patterns in RustAdvancedLoggerDxe
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
  HidPkg/UefiHidDxe/src/pointer.rs
Labels: impact:non-functional
