Repository microsoft/mu_plus, pull requests merged in 2024-01, with the labels that each got.

#402 Fix DxePagingAuditTestApp Typo, Update FlatPageTableLib AARCH64 IsPageReadable() Check
  UefiTestingPkg/AuditTests/PagingAudit/UEFI/Dxe/App/DxePagingAuditTestApp.c
  UefiTestingPkg/Library/FlatPageTableLib/AArch64/FlatPageTableAArch64.c
Labels: type:bug

#388 Add prefix for advanced logger memory message entries
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Include/AdvancedLoggerInternal.h
  AdvLoggerPkg/Include/Library/AdvancedLoggerAccessLib.h
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/AdvancedLoggerCommon.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/AdvancedLoggerCommon.h
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Pei64/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Runtime/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/Sec/AdvancedLoggerLib.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/SmmCore/AdvancedLoggerLib.c
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: impact:breaking-change, impact:testing, language:python

#404 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#406 Fixing uninitialized variable build error
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
Labels: type:bug, impact:security, impact:non-functional

#408 Wrap advanced logger buffer cursor when the logging area is full
  AdvLoggerPkg/AdvLoggerPkg.dec
  AdvLoggerPkg/AdvLoggerPkg.dsc
  AdvLoggerPkg/Library/AdvancedLoggerLib/AdvancedLoggerCommon.c
  AdvLoggerPkg/Library/AdvancedLoggerLib/BaseArm/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCore/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/MmCoreArm/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/Pei64/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/PeiCore/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/Runtime/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/Sec/AdvancedLoggerLib.inf
  AdvLoggerPkg/Library/AdvancedLoggerLib/SmmCore/AdvancedLoggerLib.inf
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.c
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.inf
Labels: impact:testing

#410 Removed references to openssllib and it's associated libraries
  AdvLoggerPkg/AdvLoggerPkg.dsc
  MfciPkg/MfciPkg.dsc
  MsCorePkg/MsCorePkg.dsc
Labels: impact:non-functional

#421 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional

#414 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:testing, impact:non-functional

#411 Add call to HdwPortInitialize() when instantiating logger in DXE
  AdvLoggerPkg/Library/AdvancedLoggerLib/DxeCore/AdvancedLoggerLib.c
Labels: type:bug, type:design-change

#417 Fixing Advanced logger wrapping unit test
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.c
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.inf
Labels: impact:testing, impact:non-functional

#423 [CHERRY-PICK] Fixing Advanced logger wrapping unit test (#417)
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.c
  AdvLoggerPkg/UnitTests/AdvancedLoggerWrapper/AdvancedLoggerWrapperTestApp.inf
Labels: impact:testing, impact:non-functional

#415 Adding a more adapt python tooling for Advanced Logger v4
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Library/AdvLoggerMmAccessLib/AdvLoggerMmAccessLib.c
  AdvLoggerPkg/Library/AdvLoggerSmmAccessLib/AdvLoggerSmmAccessLib.c
Labels: language:python

#424 [CHERRY-PICK] Adding a more adapt python tooling for Advanced Logger v4 (#415)
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Library/AdvLoggerMmAccessLib/AdvLoggerMmAccessLib.c
  AdvLoggerPkg/Library/AdvLoggerSmmAccessLib/AdvLoggerSmmAccessLib.c
Labels: language:python
