Repository microsoft/mu_plus, pull requests merged in 2025-03, with the labels that each got.

#640 Fix infinite loop issue in UsbGetFullHidDescriptor
  HidPkg/UsbHidDxe/UsbHidDxe.c
Labels: type:bug, impact:non-functional, type:backport

#641 UefiHidDxeV2: Fix Keyboard LED Sync Issue
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/key_queue.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
Labels: type:bug, type:backport

#649 SimpleWindowManagerDxe: Check absolute pointer mode to prevent division by zero
  MsGraphicsPkg/SimpleWindowManagerDxe/WindowManager.c
Labels: type:bug, type:backport

#653 Fix an issue where an uninitialized pointer was used if an EFI system partition was not present in the system.
  MsCorePkg/Library/DxeCapsulePersistenceLib/CapsulePersistence.c
Labels: type:bug, impact:security, type:backport

#645 Improve USB HID error scenario handling
  HidPkg/UsbHidDxe/UsbHidDxe.c
Labels: type:backport
