Repository microsoft/mu_plus, pull requests merged in 2025-01, with the labels that each got.

#619 Update crate dependencies to use crates.io
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/Cargo.toml
  AdvLoggerPkg/Crates/RustAdvancedLoggerDxe/src/lib.rs
  Cargo.toml
  MsWheaPkg/Crates/MuTelemetryHelperLib/Cargo.toml
  MsWheaPkg/Crates/MuTelemetryHelperLib/src/lib.rs
  MsWheaPkg/Crates/MuTelemetryHelperLib/src/status_code_runtime.rs
  MsWheaPkg/MsWheaPkg.ci.yaml
Labels: impact:non-functional, type:backport

#620 Fix event handling bug with touch and keyboard input
  MsGraphicsPkg/DisplayEngineDxe/FormDisplay.c
Labels: type:bug, type:backport

#623 [CHERRY-PICK ] Fix event handling bug with touch and keyboard input (#620)
  MsGraphicsPkg/DisplayEngineDxe/FormDisplay.c
Labels: type:bug
