Repository microsoft/mu_plus, pull requests merged in 2025-02, with the labels that each got.

#630 AdvLoggerPkg/AdvancedLoggerDxeLibGoogleTest: Link GoogleTest
  AdvLoggerPkg/Library/AdvancedLoggerLib/Dxe/GoogleTest/AdvancedLoggerDxeLibGoogleTest.inf
Labels: type:bug, impact:testing, impact:non-functional, type:backport

#632 Reset the keyboard to default state during initialization
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
Labels: type:bug, type:backport

#635 [CHERRY-PICK] [202311] Reset the keyboard to default state during initialization
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
Labels: type:bug

#634 AdvLoggerPkg: Fix message handling and LineParserTestApp
  AdvLoggerPkg/AdvLoggerPkg.ci.yaml
  AdvLoggerPkg/Library/AdvancedLoggerAccessLib/AdvancedLoggerAccessLib.c
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: type:bug, impact:breaking-change, impact:testing, type:backport

#631 DecodeUefiLog separate by size feature
  AdvLoggerPkg/Application/DecodeUefiLog/DecodeUefiLog.py
  AdvLoggerPkg/Application/DecodeUefiLog/ReadMe.md
Labels: type:documentation, impact:non-functional, language:python, type:backport
