Repository microsoft/mu_plus, pull requests merged in 2025-05, with the labels that each got.

#675 AdvLoggerPkg: Fix timestamp consistency in LineParserTestApp
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: type:bug, impact:non-functional, type:backport

#677 TpmTestingPkg, UefiTestingPkg: Update for Tpm2DebugLib Changes
  TpmTestingPkg/Overrides/Tcg2Dxe/Tcg2Dxe.c
  TpmTestingPkg/Overrides/Tcg2Dxe/Tcg2Dxe.inf
  UefiTestingPkg/AuditTests/TpmEventLogAudit/TpmEventLogAudit.c
  UefiTestingPkg/UefiTestingPkg.dsc
Labels: impact:non-functional

#676 AdvLoggerPkg: Fix timestamp consistency in LineParserTestApp
  AdvLoggerPkg/UnitTests/LineParser/LineParserTestApp.c
Labels: type:bug, impact:non-functional, type:backport

#680 XmlSupportPkg: Remove FreePool during reporting of unit tests results.
  XmlSupportPkg/Library/UnitTestResultReportJUnitFormatLib/UnitTestResultReportLib.c
Labels: type:bug, type:backport

#681 MfciPkg: MfciPolicyParsingLib Remove Debug statement.
  MfciPkg/Private/Library/MfciPolicyParsingLib/MfciPolicyParsingLib.c
Labels: type:bug, impact:non-functional, type:backport

#686 MsGraphicsPkg/QrEncoderLib: Prevent memcpy being used on VS22 (17.14.2)
  MsGraphicsPkg/Library/QrEncoderLib/QrEncoderLib.c
Labels: impact:non-functional

#682 Refine HID Touch Panel Data Handling Based on Contact Count
  HidPkg/UefiHidDxeV2/src/pointer.rs
Labels: type:design-change, type:backport

#693 MsGraphicsPkg/QrEncoderLib: Prevent memcpy being used on VS22 (17.14.2)
  MsGraphicsPkg/Library/QrEncoderLib/QrEncoderLib.c
Labels: impact:non-functional

#694 MsGraphicsPkg/QrEncoderLib: Prevent memcpy being used on VS22 (17.14.2)
  MsGraphicsPkg/Library/QrEncoderLib/QrEncoderLib.c
Labels: impact:non-functional, type:backport
