Repository microsoft/mu_plus, pull requests merged in 2025-06, with the labels that each got.

#695 Build HidDxe rust module with 1.85 compiler
  HidPkg/UefiHidDxeV2/Cargo.toml
  HidPkg/UefiHidDxeV2/src/driver_binding.rs
  HidPkg/UefiHidDxeV2/src/hid.rs
  HidPkg/UefiHidDxeV2/src/hid_io.rs
  HidPkg/UefiHidDxeV2/src/keyboard.rs
  HidPkg/UefiHidDxeV2/src/keyboard/key_queue.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in.rs
  HidPkg/UefiHidDxeV2/src/keyboard/simple_text_in_ex.rs
  HidPkg/UefiHidDxeV2/src/main.rs
  HidPkg/UefiHidDxeV2/src/pointer.rs
  HidPkg/UefiHidDxeV2/src/pointer/absolute_pointer.rs
Labels: type:backport

#701 [Cherry-pick] Remove override tag for display engine
  MsGraphicsPkg/DisplayEngineDxe/DisplayEngineDxe.inf
Labels: impact:non-functional, type:backport

#699 [CHERRY-PICK] Refine HID Touch Panel Data Handling Based on Contact Count
  HidPkg/UefiHidDxeV2/src/pointer.rs
Labels: type:backport

#705 codeql.yml: Always download cargo make
  .github/workflows/codeql.yml
Labels: impact:non-functional, type:backport

#710 [CHERRY-PICK] codeql.yml: Always download cargo make
  .github/workflows/codeql.yml
Labels: impact:non-functional, type:backport

#713 MsGraphicsPkg/DisplayEngineDxe: Remove override hash
  MsGraphicsPkg/DisplayEngineDxe/DisplayEngineDxe.inf
Labels: impact:non-functional
