Repository microsoft/mu_plus, pull requests merged in 2025-04, with the labels that each got.

#654 Fix an issue where an uninitialized pointer was used if an EFI system…
  MsCorePkg/Library/DxeCapsulePersistenceLib/CapsulePersistence.c
Labels: impact:security, type:backport

#666 Run CI using release branches of dependent repos
  .pytool/CISettings.py
Labels: impact:non-functional

#662 Updating MuSecureBootKeySelectorLib to detect MS Serviced
  MsCorePkg/Include/Library/MuSecureBootKeySelectorLib.h
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.c
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.inf
Labels: impact:breaking-change, type:design-change, type:feature-request, impact:non-functional, type:backport

#670 Temp Revert of "Updating MuSecureBootKeySelectorLib to detect MS Serviced"
  MsCorePkg/Include/Library/MuSecureBootKeySelectorLib.h
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.c
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.inf
Labels: impact:non-functional

#669 [CHERRY-PICK] Add "Updating MuSecureBootKeySelectorLib to detect MS Serviced" for backport
  MsCorePkg/Include/Library/MuSecureBootKeySelectorLib.h
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.c
  MsCorePkg/Library/MuSecureBootKeySelectorLib/MuSecureBootKeySelectorLib.inf
Labels: impact:breaking-change, impact:non-functional, type:backport
